name: Lint

on:
  push:
    branches: [develop*, main]
  pull_request:
    branches: [develop*, main]

jobs:
  bun-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: "Install Dependencies"
        run: |
          bun install

      - name: "Lint"
        run: bun lint
